```{r setup, warn = FALSE, message = FALSE}
library(tidyverse)
library(ggnewscale)
library(viridis)
ROOT_DIR <- "/mnt/isilon/sfgi/dudekm/"
```

```{r}
ldsr_results_full <- read.delim("ldsr_results.tsv")
trait_summary <- read.delim("traits_summary.tsv")

ldsr_results_full <- ldsr_results_full %>%
  mutate(sumstats_source = ifelse(grepl("PASS_|UKB_", Trait), "alkesgroup", "curated"))


traits <- c(
  "NAFLD", "BMI", "child_obesity", "T2D", "lipids_HDL", "lipids_LDL", 
  "lipids_nonHDL", "lipids_TC", "lipids_TG", "hepB", "hepC",
  "autoimmune_hep", "cirrhosis", "PB_cholangitis",
  "DrnkWk", "AgeSmk", "CigDay", "SmkCes", "SmkInit", "height",
  "AD", "insomnia", "glaucoma", "BIP", "SCZ", "ALT", "ALP", "GGT"
)

traits_names <- c(
  "MASLD", "BMI", "Child Obesity", "T2D", "Lipids HDL", "Lipids LDL", 
  "Lipids nonHDL", "Lipids TC", "Lipids TG", "hepB", "hepC",
  "autoimmune_hep", "cirrhosis", "PB_cholangitis",
  "DrnkWk", "AgeSmk", "CigDay", "SmkCes", "SmkInit", "height",
  "AD", "insomnia", "glaucoma", "BIP", "SCZ", "ALT", "ALP", "GGT"
)

liver_traits <- c("BMI", "T2D", "MASLD", "ALT", "ALP", "GGT",
                  "Lipids HDL", "Lipids LDL", "Lipids nonHDL", "Lipids TC", "Lipids TG")

ldsr_results <- ldsr_results_full %>%
  dplyr::filter(sumstats_source == "curated") %>%
  mutate(
    Trait = factor(Trait, levels = traits),
    significant = !is.na(P) & P < 0.05,
  )
  

levels(ldsr_results$Trait) <- traits_names
```

Load ldsr results for liver open chromatin
```{r}
ldsr_results_ocr <- read.delim(paste0(ROOT_DIR, "v2g_mapping_liver/ldsr/ldsr_results.tsv"))

ldsr_results_ocr <- 
  ldsr_results_ocr %>%
  filter(Annotation == "brandon_liver_ocr") %>%
  mutate(
    Trait = factor(Trait, levels = traits),
    significant = !is.na(P) & P < 0.05,
  )

levels(ldsr_results_ocr$Trait) <- traits_names
  
```


```{r fig.height=10, fig.width=12}
ldsr_results %>%
  filter(Trait != "autoimmune_hep") %>%
  mutate(
    xmin = ifelse(Enrichment < 0, 0, Enrichment - Enrichment_std_error),
    xmin = pmax(xmin, 0),
    xmax = ifelse(Enrichment < 0, 0, Enrichment + Enrichment_std_error),
    Enrichment = pmax(Enrichment, 0)
  ) %>%
  ggplot(aes(x = Enrichment, y = Trait, color = -log10(P), 
             size = Prop_SNPs, shape = Enrichment == 0)) + 
  geom_vline(xintercept = 1) +
  geom_pointrange(aes(xmin = xmin, 
                      xmax = xmax)) +
  geom_point(data = . %>% filter(significant), shape = "*", color = "black") + 
  scale_shape_manual(name = "Negative\nEnrichment", values = c(16, 4)) +
  scale_size_continuous(range = c(0.5, 3)) +
  scale_color_viridis(option = "plasma", limits = c(0, NA), name = bquote(-log[10](p)), direction = -1) +
  coord_cartesian(xlim = c(-1, 400)) +
  scale_x_log10() +
  facet_wrap(~Annotation, ncol = 4) +
  theme_bw()

ggsave("figures/fpQTLs_ldsr.png", width = 12, height = 10, units = "in")
```

# MANUSCRIPT - Figure 4B
```{r fig.width=5, fig.height=4.5}
liver_traits <- c("BMI", "T2D", "MASLD", "ALT", "ALP", "GGT",
                  "Lipids HDL", "Lipids LDL", "Lipids nonHDL", "Lipids TC", "Lipids TG")

traits.name <- c("BMI", "T2D", "MASLD", "Enzymes\nALT", "Enzymes\nALP", "Enzymes\nGGT", "Lipids\nHDL", "Lipids\nLDL", "Lipids\nnonHDL", "Lipids\nTC", "Lipids\nTG")

ldsr_results %>%
  filter(Trait %in% liver_traits) %>%
  mutate(Trait = factor(Trait, levels = rev(liver_traits))) %>%
  filter(Annotation == "PRINT_no_gaussian") %>%
  mutate(
    xmin = ifelse(Enrichment < 0, 0, Enrichment - Enrichment_std_error),
    xmin = pmax(xmin, 0),
    xmax = ifelse(Enrichment < 0, 0, Enrichment + Enrichment_std_error),
    Enrichment = pmax(Enrichment, 0)
  ) %>%
  ggplot(aes(x = Enrichment, y = Trait, color = -log10(P), shape = Enrichment == 0)) + 
  geom_vline(xintercept = 1) +
  geom_pointrange(aes(xmin = xmin, 
                      xmax = xmax), size = 2) +
  geom_point(data = . %>% filter(significant), shape = "*", color = "black") + 
  scale_shape_manual(name = "Negative\nEnrichment", values = c(16, 4), guide = NULL) +
  scale_color_viridis(option = "plasma", limits = c(0, NA), name = bquote(-log[10](p)), direction = -1) +
  coord_cartesian(xlim = c(-1, 400)) +
  scale_x_log10() +
  scale_y_discrete(labels = rev(traits.name)) +
  theme_bw()

ggsave("figures/fpQTLs_ldsr_new.png", width = 5, height = 4.5, units = "in")
```

```{r fig.width=10, fig.height=20}

ldsr_results_full %>%
  filter(sumstats_source == "alkesgroup") %>%
  filter(Annotation == "PRINT_no_gaussian") %>%
  arrange(P) %>%
  head(30) %>%
  mutate(
    xmin = ifelse(Enrichment < 0, 0, Enrichment - Enrichment_std_error),
    xmin = pmax(xmin, 0),
    xmax = ifelse(Enrichment < 0, 0, Enrichment + Enrichment_std_error),
    Enrichment = pmax(Enrichment, 0)
  ) %>%
  ggplot(aes(x = Enrichment, y = Trait, color = -log10(P), shape = Enrichment == 0)) + 
  geom_vline(xintercept = 1) +
  geom_pointrange(aes(xmin = xmin, 
                      xmax = xmax), size = 2) +
  geom_point(data = . %>% filter(P < 0.05), shape = "*", color = "black") + 
  scale_shape_manual(name = "Negative\nEnrichment", values = c(16, 4), guide = NULL) +
  scale_color_viridis(option = "plasma", limits = c(0, NA), name = bquote(-log[10](p)), direction = -1) +
  coord_cartesian(xlim = c(-1, 400)) +
  scale_x_log10() +
  theme_bw()
```

```{r fig.height=10, fig.width=12}
ldsr_results %>%
  filter(Trait %in% liver_traits) %>%
  filter(grepl("PRINT_no_gaussian", Annotation, fixed = TRUE)) %>%
  mutate(
    xmin = ifelse(Enrichment < 0, 0, Enrichment - Enrichment_std_error),
    xmin = pmax(xmin, 0),
    xmax = ifelse(Enrichment < 0, 0, Enrichment + Enrichment_std_error),
    Enrichment = pmax(Enrichment, 0)
  ) %>%
  ggplot(aes(x = Enrichment, y = Trait, color = -log10(P), 
             size = Prop_SNPs, shape = Enrichment == 0)) + 
  geom_vline(xintercept = 1) +
  geom_pointrange(aes(xmin = xmin, 
                      xmax = xmax)) +
  geom_point(data = . %>% filter(significant), shape = "*", color = "black") + 
  scale_shape_manual(name = "Negative\nEnrichment", values = c(16, 4)) +
  scale_size_continuous(range = c(0.5, 3)) +
  scale_color_gradient(low = "gold", high = "purple") +
  coord_cartesian(xlim = c(-1, 400)) +
  scale_x_log10() +
  facet_wrap(~Annotation, ncol = 4) +
  theme_bw()
```

```{r fig.width=5, fig.height=5}
ldsr_results_ocr %>%
  filter(Trait %in% liver_traits) %>%
  mutate(Trait = factor(Trait, levels = rev(liver_traits))) %>%
  mutate(
    xmin = ifelse(Enrichment < 0, 0, Enrichment - Enrichment_std_error),
    xmin = pmax(xmin, 0),
    xmax = ifelse(Enrichment < 0, 0, Enrichment + Enrichment_std_error),
    Enrichment = pmax(Enrichment, 0)
  ) %>%
  ggplot(aes(x = Enrichment, y = Trait, color = -log10(P))) + 
  geom_vline(xintercept = 1) +
  geom_pointrange(aes(xmin = xmin, 
                      xmax = xmax), size = 2) +
  geom_point(data = . %>% filter(significant), shape = "*", color = "black") + 
  scale_color_gradient(low = "gold", high = "purple", limits = c(0, NA)) +
  coord_cartesian(xlim = c(-1, 3)) +
  scale_x_log10() +
  theme_bw()

ggsave("figures/brandon_liver_ocr_ldsr.png", width = 5, height = 5, units = "in")
```



